version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  backend:
    build: .
    container_name: backend
    ports:
      - 3000:3000
    command: bash -c "rm -f /tmp/pids/server.pid && bundle exec rails s -p '3000' -b '0.0.0.0'"
    volumes:
      - .:/app_name
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - mysql
    tty: true
    stdin_open: true
